### ISSUE TITLE
malformed emperor: ~gal

### ISSUE THREAD

**Issue by seekr** [solri-urbit/arvo#16]
when creating a galaxy using `urbit -cI gal -A ~/arvo pier` I get a `malformed emperor: ~gal` message and urbit terminates without asking me for generator...

**Comment by sorpaas** [comment]
You'll need to substitute "gal" with an actual galaxy name like "zod".

The complete list of all valid galaxy names are here https://github.com/solri/arvo/blob/maint-20170614/arvo/ames.hoon#L145
